### ISSUE TITLE
[Regarding fonts.pickle file]

### ISSUE THREAD

**Issue by huan0502** [CyberAgentAILab/OpenCOLE#20]
Hi, great work guys. Thank you so much for this contribution.

I'm trying out the model and adapting it to another language different than English so the ability to control the fonts list is a big concern.

I have a favor to ask. Can you guys release a sample font json metadata and asset so that I can try to build a new pickle file based on that. I'm a bit confused about what metadata fields should be included in the json and is the asset in the form of .ttf ? 
Working examples to test with FontManager would be really appreciated, just 1 font is enough

You can email me at huanpham05@gmail.com if you prefer not to pollute the code base.

Thank you for your time and effort!

**Comment by naoto0804** [comment]
Hi, thank you for your interest in our project! As we do [here](https://github.com/CyberAgentAILab/OpenCOLE/blob/eb370faa17be8711bd7d8e907d8a22640db56109/src/opencole/renderer/renderer.py#L21-L27)

```
import huggingface_hub

path = huggingface_hub.hf_hub_download(
    repo_id="cyberagent/opencole",
    filename="resources/fonts.pickle",
    repo_type="dataset",
)

print(path)  # this is where the pickle is stored
```

**Comment by huan0502** [comment]
Thanks for your reply. 
I have found and inspected the fonts.pickle. I have managed to add additional fonts.

Great work team, thank you and wish you all the best
