### ISSUE TITLE
GPT4 augment prompt

### ISSUE THREAD

**Issue by laxlyezhi** [CyberAgentAILab/OpenCOLE#4]
I found the test prompt in cole_designerintention_v1_samples had gpt4 augmented prompt.
How to augment the original prompt? Could you give the gpt4 prompt?

**Comment by naoto0804** [comment]
Hi, the augmented prompt is provided by the original [COLE](https://arxiv.org/abs/2311.16974). I checked the paper but could not find the exact prompt fed to GPT4. Please ask it to the original COLE authors, and it would really appreciate it if you also share it with me;

**Comment by naoto0804** [comment]
Feel free to open if you want to discuss more!
