### ISSUE TITLE
About the arguments specified for inference

### ISSUE THREAD

**Issue by pacifinapacific** [CyberAgentAILab/OpenCOLE#7]
Thank you for publishing the code.
I have a question because I do not fully understand the contents of the repository.
What are <INPUT_HFDS> and <DETAIL_DIR> required for inference? Are they included in the repository or in the contents of the hugging face?
It would be helpful if you could share the demo code for inference

**Comment by naoto0804** [comment]
Hi, thank you for your interest in our repo.

- INPUT_HFDS is typically a `cyberagent/opencole`, which is hosted in the HuggingFace dataset hub.
- DETAIL_DIR indicates the directory containing the predicted results of `opencole.inference_launcher.k_shot_llm` (see [doc](https://github.com/CyberAgentAILab/OpenCOLE/blob/main/docs/inference.md#k-shot-llm))

Hope it helps!

**Comment by pacifinapacific** [comment]
I got it. Thank you very much!
